version: 0.1.{build}
branches:
  only:
    - master
image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
clone_depth: 1
environment:
  matrix:
    - vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat
    - vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
matrix:
  fast_finish: true
install:
  - call "%vcvars%"
build_script:
  - nmake -f Makefile.mak
