language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - CC=gcc-5
         - CXX=g++-5
    - os: osx
script:
  - ./autogen.sh && ./configure && make
